config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "chats#index"

  resources :chats, only: [:index, :new, :show, :create] do
    resources :messages, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  acts_as_chat

  has_many :messages

  scope :ordered, -> { order(created_at: :desc) }

  class << self
    def sale(params)
      new(params.with_defaults(model_id: DEFAULT_MODEL_ID))
    end

    def find_sale(id)
      chat = find(id)
      chat.tool_enabled!
      chat
    end

    DEFAULT_MODEL_ID = "gpt-4-turbo"
  end

  def tool_enabled!
    with_tools(ProductTool, OrderTool)
  end

  def activate_sales_assistant_mode!
    with_instructions(
      "You are a sales assistant. Your goal is to help the customer finding the best product for their needs."
    )
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :tool_call, optional: true

  acts_as_message

  enum :role, %w[user system assistant tool].index_by(&:to_sym)

  def user_friendly?
    content.present? && (user? || assistant?)
  end
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_tool.rb
class OrderTool < RubyLLM::Tool
  description "Place an order for a product. When the user asks for an order, ensure the user has provided the necessary information to place an order."

  param :product
  param :first_name
  param :last_name
  param :address
  param :phone_number
  param :email

  def execute(product:, first_name:, last_name:, address:, phone_number:, email:)
    Order.create!(
      product: product,
      first_name: first_name,
      last_name: last_name,
      address: address,
      phone_number: phone_number,
      email: email
    )

    "Order placed successfully"
  end
end

app/models/product_tool.rb
class ProductTool < RubyLLM::Tool
  description "Return products available for shopping. When the user asks for products, return the products."

  def execute
    products = [
      {
        name: "Lipstick",
        price: 10,
        description: "A lipstick with a matte finish"
      },
      {
        name: "Shoe",
        price: 20,
        description: "A shoe with a leather finish"
      },
      {
        name: "T-shirt",
        price: 30,
        description: "A t-shirt with a cotton finish"
      }
    ]
    products.to_json
  end
end

app/models/tool_call.rb
class ToolCall < ApplicationRecord
  belongs_to :message

  acts_as_tool_call
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chats = Chat.ordered
    @chat = Chat.new
  end

  def show
    @chat = Chat.find(params[:id])
  end

  def create
    @chats = Chat.ordered
    @chat = Chat.sale(chat_params)

    if @chat.save
      @chat.activate_sales_assistant_mode!
      render :create
    else
      render :new
    end
  end

  private

  def chat_params
    params.require(:chat).permit(:name)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chat = Chat.find_sale(params[:chat_id])
    @chat.ask(message_params[:content])
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/_list.haml
= turbo_frame_tag "chats" do
  %ul
    - chats.each do |chat|
      %li
        = button_to chat.name, chat_path(chat, format: :turbo_stream), method: :get

app/views/chats/_messages.haml
= turbo_frame_tag "active_chat_messages" do
  %h1= "Chat: #{chat.name}"

  %ul
    - chat.messages.each do |message|
      - if message.user_friendly?
        %li
          %strong= "#{message.role}: "
          = message.content

  - if chat.persisted?
    = form_with model: Message.new, url: chat_messages_path(chat_id: chat.id) do |f|
      = f.text_area :content, placeholder: "Message", autofocus: true, rows: 3, cols: 200
      = f.submit "Send"

app/views/chats/create.turbo_stream.haml
= turbo_stream.replace("active_chat_messages") do
  = render "chats/messages", chat: @chat

= turbo_stream.replace("chats") do
  = render "chats/list", chats: @chats

app/views/chats/index.haml
%h1 Chats

.d-flex.gap-1
  %aside
    = render "chats/list", chats: @chats

    %h2 New chat

    = form_with model: @chat do |f|
      = f.text_field :name, placeholder: "Chat name", autofocus: true, required: true, minlength: 3, maxlength: 20

      = f.submit "Create chat"

  %main
    = turbo_frame_tag "active_chat_messages" do
      = render "chats/messages", chat: @chat

app/views/chats/show.turbo_stream.haml
= turbo_stream.replace("active_chat_messages") do
  = render "chats/messages", chat: @chat

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Zipchat Challenge" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/create.turbo_stream.haml
= turbo_stream.replace("active_chat_messages") do
  = render "chats/messages", chat: @chat